# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'spec/**/*'
    - 'vendor/bundle/**/*'
    - 'Rakefile'
    - 'app_info.gemspec'
    - 'lib/app-info.rb'
    - 'lib/app_info/protobuf/models/*_pb.rb'
    - 'main.rb'

Layout/LineLength:
  Max: 100
  Exclude:
    - 'lib/app_info/helper/signatures.rb'
    - 'lib/app_info/android/signatures/info.rb'
    - 'lib/app_info/apk.rb'

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/app_info/file.rb'

Lint/UselessAssignment:
  Exclude:
    - 'lib/app_info/android/signatures/v3.rb'

Metrics/AbcSize:
  Max: 100

Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'lib/app_info/mobile_provision.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'lib/app_info/mobile_provision.rb'
    - 'lib/app_info/android/signatures/v2.rb'
    - 'lib/app_info/android/signatures/v3.rb'

Metrics/ParameterLists:
  Exclude:
    - 'lib/app_info/helper/signatures.rb'

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 18

Metrics/BlockNesting:
  Exclude:
    - 'lib/app_info/dsym.rb'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/PerlBackrefs:
  Exclude:
    - 'lib/app_info/core_ext/string/inflector.rb'

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/ClassVars:
  Enabled: false

Lint/UselessConstantScoping:
  Enabled: false
